### ISSUE TITLE
Likelihood Issues Inventory

### ISSUE THREAD

**Issue by evanbiederstedt** [evanbiederstedt/CMBintheLikeHoodz#2]
An extensive catalog of issues encountered so far: 

ISSUE (1): The killer is this operation 

`summatrix = np.sum( [eval_legendre(i, dotproductmatrix) for i in ell], axis=0)`

That makes Nside=16 extremely slow, and Nside=32 virtually impossible (at least, it freezes up my browser). 

GOAL: Come up with better algorithmic methods/strategies to tackle this. Consider a different language (e.g. FORTRAN90, C, etc.), but that won't help much. Nside=32 is still 12288 by 12288 and that's not even counting all the of Legendre polynomial coefficients. Consider trying C++ eigen http://eigen.tuxfamily.org/index.php?title=Main_Page
or parallell computing 
or a supercomputer
or GPU computing (not bad idea---whom should we talk to?)
or loop tiling (this is a good idea) http://en.wikipedia.org/wiki/Loop_tiling
or store matrix, page a portion of the matrix into memory, take that block of matrices to perform operations, and then rinse and repeat

or http://libelemental.org/about/ (this is also a good idea...maybe)
or Julia? http://julialang.org/ 
**********

ISSUE 2: The likelihood expressions we have are NOT exact. They are approximate within some constant (2/pi somewhere?) 

GOAL:  Figure out the exact expressions. 
**********

ISSUE 3: Should we include monopole and dipole values? This is related to which lmax value to use. 

Larger problem is that the spherical harmonic space likelihood *requires* that you *do not* use the monopole and dipole values. Why? You cannot divide by zero!
However (and this is strange) you *should* use the monopole and dipole values for the real-space likelihood function. This gives realistic answers, and is the default when you input temperature values from sky maps. 

GOAL: Who knows....
**********

ULTIMATE GOAL: If we can get Nside=32, we are set! We are within COBE territory, e.g. see http://iopscience.iop.org/1538-4357/464/1/L25/pdf/5019.pdf

**Comment by davidwhogg** [comment]
does eval_legendre take a vector of ints instead of i?

**Comment by evanbiederstedt** [comment]
@davidwhogg If I understand you correctly: the scipy special function eval_legendre is a universal function, i.e. it is a function that operates on ndarrays in an element-by-element fashion, supporting array broadcasting, type casting, etc. It takes as an argument order of polynomial 'n' (ndarray of ints) and polynomial arguments 'x' (ndarray of floats64). 
http://docs.scipy.org/doc/numpy/reference/ufuncs.html

A quick test can show this---I'll upload a file. I also have a script writing our own Rodrigues formula P_n(x) using the recurrence relation, rewritten from an old F77 numerical recipes book (I think). We can compare/contrast.

**Comment by davidwhogg** [comment]
If that's the case, you don't need the for loop, do you?  Can you re-write it without the for loop?

**Comment by davidwhogg** [comment]
you might need to look up "broadcasting" and start with a small set of pixels to test...

**Comment by evanbiederstedt** [comment]
Uff, you're right. Broadcasting rules are easy to understand performing element-wise multiplication on arrays of the same dimensions and shape, or on a multi-dimensional array by a scalar. Passing two arrays of different dimensions in a function and then doing the summation correctly? That threw me.

 `np.sum( eval_legendre(newellval[:, None, None], dotproductmatrix), axis=0)` speeds everything up nicely.
