### ISSUE TITLE
LF comparison, N = 0, C-3 test

### ISSUE THREAD

**Issue by evanbiederstedt** [evanbiederstedt/CMBintheLikeHoodz#3]
This issue refers to: July1_CMB_Likelihoods_Noiseless_LogLF.ipynb

https://github.com/evanbiederstedt/CMBintheLikeHoodz/blob/master/Likelihood_Comparison/July1_CMB_Likelihoods_Noiseless_LogLF.ipynb

Re-writing the logLF into a function that takes parameters we've generated. Prints out all matrix values and parameters to check. 

VALUES
CAMB Boltzmann-code generated C_3:                              5.88275e-10
Healpix output from sky map (i.e. data input) \hat{C}_3 :    1.53198686892e-10
Sky map output a3m, abs() and squared:     a30    a31    a32     a33 
[  8.84771791e-13   8.06516529e-18   3.85347491e-12   7.58705140e-11]

It therefore seems reasonable to generate values for parameter "C_3" as from 1e-10 to 9e-10

Using these parameters (we generate 20), our output from the logLF function is:

[ -2.16959893e+19  -2.65398526e+18   1.42710194e+19  -1.26463401e+18
  -1.03857802e+18  -4.20116627e+17   4.12001169e+18   2.73781710e+19
  -1.44487201e+18  -6.35095812e+16   1.06598819e+18   7.81468088e+18
  -1.27041910e+18  -1.38157562e+18   3.81904100e+18  -7.52039023e+17
   2.45900217e+17  -3.65626336e+17  -1.92729866e+18   9.80260447e+16]

The m^T C^-1 m term is:

[ -2.16959893e+19  -2.65398526e+18   1.42710194e+19  -1.26463401e+18
  -1.03857802e+18  -4.20116627e+17   4.12001169e+18   2.73781710e+19
  -1.44487201e+18  -6.35095812e+16   1.06598819e+18   7.81468088e+18
  -1.27041910e+18  -1.38157562e+18   3.81904100e+18  -7.52039023e+17
   2.45900217e+17  -3.65626336e+17  -1.92729866e+18   9.80260447e+16]

The logdet C term is:

array([-172124.25514124, -170882.41059328, -170194.63227924,
       -169621.9113563 , -168918.38584806, -168505.61472957,
       -168177.24536938, -167900.66900411, -167612.82339294,
       -167212.86858438, -166887.63800854, -166653.137683  ,
       -166445.67892491, -166273.52904962, -166115.15628115,
       -165951.5126291 , -165821.84861467, -165693.11092926,
       -165541.54634516, -165387.3800084 ]))

The constant N 2pi is 
19301.9452637

**Comment by evanbiederstedt** [comment]
This issue is mostly like the inverse matrix. See line 68. 

S_ij has values xxxxx e-11

It's inverse has values xxxxx e+24

This is probably why m^t C^-1 m is consistently so large....

**Comment by davidwhogg** [comment]
Just multiply the CMB maps by 1e6 and the C matrix entries by 1e12 and try again.

All that matter are likelihood *differences* not values, so none of this matters except that you are pushing numerical underflow in the IEEE numbers

**Comment by evanbiederstedt** [comment]
July1_CMB_Likelihoods_NoiselessLogLF_test2.ipynb

Rescale CMB pixel values (i.e. "tempval" to "tempp") and S_ij entries ("Sij" to "newSij"). 

#
# multiply the CMB maps by 1e6 and the C matrix entries by 1e12 and try again.
#
tempp = (1e6)*tempval # multiply CMB maps by 1e6



def LogLikehood(param):
    # param is our parameter, C_3
    Sij = param[:, None, None] * norm_matrix[1][None, :, :]
    newSij = (1e12)*Sij   # multiply S_ij by 1e12
    # Format 7/4pi * param * P_3(M) where param is the parameter we vary, C_l
    # Sij.shape = (50, 3072, 3072)
    invSij = np.linalg.inv(newSij)
    logdetC = np.linalg.slogdet(Sij)  # returns sign and determinant; use logdetC[1]
    # model_fit_terms = m^T C^-1 m
    model_fit_terms = np.array([np.dot(tempp.T , np.dot(invSij[i] , tempp) ) for i in range(invSij.shape[0])])
    return model_fit_terms + logdetC[1] + Npix2pi


OUTPUT

In [68]:

LogLikehood(vary_x_samples1)
Out[68]:
array([ -1.38019546e+19,  -1.23446202e+17,  -2.74672691e+19,
        -4.42319414e+18,  -4.82694695e+18,   4.00881257e+18,
        -8.44983107e+18,  -3.52283985e+17,  -3.89031428e+19,
         3.27733403e+18,  -2.58568750e+18,  -7.54497429e+17,
        -1.20798640e+18,  -1.26752062e+18,  -4.86506776e+17,
         1.59250768e+18,  -7.03372689e+18,  -2.52215883e+18,
         2.78197480e+18,  -2.30797783e+18])

I may try rescaling until we get values less that 1, preferably between 0 and 1.

**Comment by davidwhogg** [comment]
Notice that the m C m term remains the same (dimensionless!) and the logdet(C) term will change.  But what won't change is the values of likelihood *differences* and you have now got linear algebra that isn't close to underflow.

**Comment by davidwhogg** [comment]
(ps. if you don't have that invariance, you have another bug).
