### ISSUE TITLE
LF test, values used by Healpix routines

### ISSUE THREAD

**Issue by evanbiederstedt** [evanbiederstedt/CMBintheLikeHoodz#5]
There is a significant spread between our calculated values: 

The array of a3m_squared, i.e. a30, a31, a32, a33 is 
[  8.84771791e-13      
8.06516529e-18   
3.85347491e-12   
7.58705140e-11]. 

However, the calculated power spectrum C_3 is 1.53198686892e-10. The variance 7*hatC3 equals 1.07239080824e-09.

***********

Note the values calculated with our temperature map by Healpix routines:

The variance Var(a_lm) = (2 * l +1)C_l 

The anafast routine outputs the power spectrum \hat{C}_l = 1\(2 * l +1) || a_lm ||^2

The same routine map2alm outputs the corresponding a_lm values. 

For our map:

The array of a3m_squared, i.e. a30, a31, a32, a33 is 
[  8.84771791e-13   8.06516529e-18   3.85347491e-12   7.58705140e-11]. 

a30 is 9.40623086569e-07
a31 is 2.8399234655e-09
a32 is 1.96302697687e-06
a33 is -8.71036819164e-06

The value \hat{C}_3 is 1.53198686892e-10. 
The variance for this value (2l+1)C_l is 7*hatC3, which equals 1.07239080824e-09

**Comment by davidwhogg** [comment]
how did you get the "calculated power spectrum C_3" and how did you get the "variance 7 * hatC3"?  Particularly the former -- is it the optimum of a likelihood?  If so, can you show me the plot of likelihood vs C_3?

**Comment by evanbiederstedt** [comment]
"Calculated power spectrum C_3" is the calculated output from our temperature map using the Healpix routine anafast, http://healpix.jpl.nasa.gov/html/facilitiesnode7.htm

It is what I'm calling "\hat{C}_l". 

It is confusing that \hat{C}_3 is so different from the a3m values. 

For plots, see https://github.com/evanbiederstedt/CMBintheLikeHoodz/blob/master/Likelihood_Comparison/July2_CMB_LogLF_Plots_Noiseless2.ipynb

https://github.com/evanbiederstedt/CMBintheLikeHoodz/blob/master/Likelihood_Comparison/July2_CMB_LFtestC3_PlotswithNoise.ipynb

Note the color scheme.

**Comment by evanbiederstedt** [comment]
"how did you get the "calculated power spectrum C_3" and how did you get the "variance 7 * hatC3"? "

More clear answer: these are calculated with Healpix. 
Variance 7*hatC_3 is calculated by multiplying by 7. 

There's a profound difference between \hat{C}_3 (what we calculate) and || alm ||**2 (what we calculate). 

However, \hat{C}_3 and the theoretical Boltzmann-code output C_3 are fairly close:

Theory C_3 is 5.88275e-10
Calculated \hat{C}_3 is 1.53198686892e-10.

**Comment by davidwhogg** [comment]
I still don't understand.  There are three values of C_3 you are throwing around.  How were the three values calculated?  Remember, I don't have a psychic knowledge of your code.

**Comment by evanbiederstedt** [comment]
Check "C3_test_sanity.ipynb"

https://github.com/evanbiederstedt/CMBintheLikeHoodz/blob/master/Likelihood_Comparison/C3_test_sanity.ipynb

The last box details all inputs, datas and parameters. 

There are two C_3's:

(1) The CAMB Boltzmann-code output. This is "C3" (I should change this to theoryC3).
The value I have is 5.88275e-10

(2) The calculated C_3 from the temperature map. This is "hatC3" (using Healpix notation). 
The value I calculate is 1.53198686892e-10.

(Healpix notation is \hat{C}_l = 1/(2*l+1) || a_lm ||^2 )

There is also: 
(3) "vary_x_samples" which should be called "vary_C3_parameter", because that's what we're doing to plot the LF

My point is that our calculations for a3m i.e. a30, a31, a32, a33 are not what we would expect.
Var(a3m) = || a3m ||**2 gives values 

[ 8.84771791e-13     8.06516529e-18    3.85347491e-12     7.58705140e-11]

See what I mean? These values are calculated using the same temperature map.

**Comment by evanbiederstedt** [comment]
Then again, perhaps it's the temperature map I'm using (which should be ok):

Using the CAMB output temperature maps, I find more "expected" values:

July6_C3_test_sanity_test2.ipynb

https://github.com/evanbiederstedt/CMBintheLikeHoodz/blob/master/Likelihood_Comparison/July6_C3_test_sanity_test2.ipynb

Here, the output a30, a31, a32, a33 is
[  3.54786292e-05   6.92273981e-09   7.65807283e-07   2.69713403e-05]

and the squared values are
[  1.25873313e-09   4.79243265e-17   5.86460794e-13   7.27453196e-10]

The "hatC3" value calculated from the CAMB sky map is  1.53198686892e-10.

**Comment by davidwhogg** [comment]
I want to see a comparison of what you call "calculated C_3" although that terminology is terrible: EVERYTHING is calculated.  I would call it "empirical C_3".  Compare that to the likelihood function!  Still waiting for this, or at least I can't find it among the dozens of ipynbs.  One single ipynb would be better than all of these.  Also, you should consider using version control rather than appending dates.

**Comment by evanbiederstedt** [comment]
I" want to see a comparison of what you call "calculated C_3" although that
terminology is terrible: EVERYTHING is calculated. I would call it
"empirical C_3"."

Good idea. I will call it "empirical C_3".

"Compare that to the likelihood function! Still waiting for this, or at
least I can't find it among the dozens of ipynbs. One single ipynb would be
better than all of these. "

It is the "black line" on the simple plots you are looking at.

"Also, you should consider using version control rather than appending
dates."

Yeah, things are out of control at the moment. I will open a new folder and
update from there.
